safe: true
timezone: Europe/Stockholm
markdown: kramdown

author: Alva Ray
description: 'Shiny signals, signed: Alva Ray'
live_url: http://alvaray.org
live_hostname: alvaray.org
email: signals@alvaray.org
google_analytics_id: UA-50156816-1
